BIDDER_NAMES = [
    "Internal",
    "Service Direct",
    "33 Mile Radius",
    "eLocal",
]

LEAD_TYPES = [
    "Calls",
    "Leads",
]

CALL_TASKS = [
    "Air Duct",
    "Appliance Repair",
    "Asbestos Removal",
    "Asbestos Testing",
    "Bathroom Remodel",
    "Biohazard",
    "Cabinets",
    "Chimneys",
    "Concrete Foundation",
    "Concrete Leveling",
    "Decks",
    "Doors",
    "Drainage Channel",
    "Electrician",
    "Excavation",
    "Fencing",
    "Fire Damage",
    "Flooring",
    "Garage Doors",
    "Grading",
    "Gutter Covers",
    "Gutters",
    "HVAC",
    "Hoarding",
    "Holiday Lighting",
    "Kitchen Remodeling",
    "Landscaping",
    "Lawn Mowing",
    "Locksmith",
    "Mold Removal",
    "Mold Testing",
    "Painting",
    "Pest Control",
    "Plumbing",
    "Roofing",
    "Siding",
    "Snow Removal",
    "Solar",
    "Stairlifts",
    "Tree Services",
    "Water Filtration",
    "Water Removal",
    "Waterproofing",
    "Windows",
]

LEAD_TASKS = [
    "Air Conditioning",
    "Air Duct",
    "Appliance Repair",
    "Asbestos Removal",
    "Asbestos Testing",
    "Asphalt Paving",
    "Attic Fan",
    "Backflow Install",
    "Backflow Testing",
    "Bathroom Remodel",
    "Bathtub Install",
    "Bathtub Liner Install",
    "Biohazard",
    "Boiler",
    "Ceiling Fan",
    "Chimneys",
    "Concrete Flatwork",
    "Concrete Floor",
    "Concrete Foundation",
    "Concrete Leveling",
    "Deck Painting",
    "Drain Camera",
    "Drain Unclog",
    "Drainage Channel",
    "Driveway",
    "Electrical Baseboard",
    "Electrical Inspection",
    "Electrical Panel",
    "Electrical Wiring",
    "Electrician",
    "Excavation",
    "Exhaust Fan",
    "Exterior Painting",
    "Faucet Repair",
    "Fence Painting",
    "Fencing",
    "Fire Damage",
    "Flooring",
    "Garage Doors",
    "Gas Piping",
    "Generator",
    "Grading",
    "Gutter Covers",
    "Gutters",
    "HVAC",
    "Heating",
    "Hoarding",
    "Holiday Lighting",
    "Hot Tub",
    "Interior Lighting",
    "Interior Painting",
    "Landscape Design",
    "Landscape Lighting",
    "Landscaping",
    "Lawn Aeration",
    "Lawn Cleanup",
    "Lawn Fertilizing",
    "Lawn Mowing",
    "Lawn Seeding",
    "Lawn Sodding",
    "Leak Detection",
    "Leak Repair",
    "Locksmith",
    "Mold Removal",
    "Mold Testing",
    "Network Wiring",
    "Painting",
    "Parking Lot Striping",
    "Patio",
    "Pavement Painting",
    "Pest Control",
    "Plumbing",
    "Plumbing Remodel",
    "Popcorn Ceiling",
    "Roofing",
    "Septic System",
    "Sewer Main",
    "Shower Install",
    "Siding",
    "Sink Repair",
    "Skylight",
    "Smoke Detector",
    "Snow Removal",
    "Soil Delivery",
    "Solar",
    "Sprinkler System",
    "Stump Removal",
    "Sump Pump",
    "Switches Outlets",
    "Synthetic Grass",
    "Thermostat",
    "Toilet Repair",
    "Tree Protection",
    "Tree Removal",
    "Tree Services",
    "Tree Trimming",
    "Wallpaper",
    "Water Damage",
    "Water Heater",
    "Water Main Repair",
    "Water Removal",
    "Water Treatment",
    "Waterproofing",
    "Weed Control",
    "Well Pump",
    "Windows",
    "Xeriscaping",
    "Yard Drain",
]

CALL_PEST_OPTIONS = [
    "Ants",
    "Bed Bugs",
    "Bees",
    "Birds",
    "Cockroaches",
    "Fleas",
    "Flies",
    "Insects",
    "Mice",
    "Mosquitos",
    "Raccoons",
    "Spiders",
    "Termites",
    "Wasps",
    "Wildlife",
]

CALL_JOB_TYPE_OPTIONS = [
    "Cleaning",
    "Install",
    "Refinish",
    "Repair",
]

LEAD_MATERIAL_OPTIONS = [
    "Asphalt",
    "Barbed Wire",
    "Brick",
    "Carpet",
    "Chainlink",
    "Concrete",
    "Copper",
    "Electric Pet",
    "Epoxy",
    "Gravel",
    "Laminate",
    "Metal",
    "PVC",
    "Pavers",
    "Single Ply",
    "Slate",
    "Spray Foam",
    "Stone",
    "Stucco",
    "Tar Gravel",
    "Tile",
    "Vinyl",
    "Wood",
    "Wrought Iron",
]

LEAD_PROPERTY_TYPE_OPTIONS = [
    "Business",
    "Residence",
]

LEAD_JOB_TYPE_OPTIONS = [
    "Cleaning",
    "Install",
    "Refinish",
    "Repair",
    "Resurface",
    "Sealing",
]
